name: Build Executável Automático

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Alterado para 3.11 (versão mais compatível)

    - name: Gerar requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        # Gera requirements.txt ignorando arquivos não-Python e diretórios problemáticos
        pipreqs src/ --force --savepath requirements.txt --ignore *.json,*.txt,assets
        # Adiciona manualmente as dependências críticas
        echo "pyinstaller" >> requirements.txt
        echo "bcrypt==4.1.2" >> requirements.txt
        echo "cffi==1.16.0" >> requirements.txt
        echo "pywin32==306" >> requirements.txt
        # Corrige outras dependências detectadas incorretamente
        sed -i '/python_bcrypt/d' requirements.txt
        type requirements.txt

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Obter versão
      id: get_version
      run: |
        $version = Get-Content -Path src/version.txt -Raw
        $version = $version.Trim()
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Gerar executável
      run: |
        pyinstaller --onefile --windowed --name SineApp `
        --add-data "src/assets/icons/*;assets/icons/" `
        --add-data "src/config.json;." `
        --add-data "src/version.txt;." `
        src/main.py

    - name: Publicar no GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SineApp.exe
        tag_name: v${{ steps.get_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}