name: Build Executável

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15  # Aumente o tempo limite

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install PySide6==6.5.3 pyinstaller==5.13.0 psycopg2-binary==2.9.6 python-dotenv==0.21.1 requests==2.31.0

    - name: Gerar executável
      run: |
        pyinstaller --onefile --windowed --name SineApp `
        --add-data "src/assets/icons/*;assets/icons/" `
        --add-data "src/config.json;." `
        --add-data "src/version.txt;." `
        src/main.py

    - name: Publicar no GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SineApp.exe
        tag_name: v$(cat src/version.txt)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}