name: Build Executável

on:
  push:
    branches: [main]

permissions:
  contents: write  # ✅ Permissão para criar releases

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyinstaller psycopg2-binary python-dotenv requests

    - name: Obter versão
      id: get_version
      run: |
        $version = Get-Content -Path src/version.txt -Raw
        $version = $version.Trim()
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Gerar executável
      run: |
        pyinstaller --onefile --windowed --name SineApp `
        --add-data "src/assets/icons/*;assets/icons/" `
        --add-data "src/config.json;." `
        --add-data "src/version.txt;." `
        src/main.py

    - name: Publicar no GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SineApp.exe
        tag_name: v${{ steps.get_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}