name: Build Executável Automático

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20  # Aumentado para builds complexas

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Gerar requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pipreqs src/ --force --savepath requirements.txt --ignore *.json,*.txt,assets
        echo "pyinstaller==6.8.0" >> requirements.txt  # Versão específica testada
        echo "bcrypt==4.1.2" >> requirements.txt
        echo "cffi==1.16.0" >> requirements.txt
        echo "pywin32==306" >> requirements.txt
        sed -i '/python_bcrypt/d' requirements.txt
        type requirements.txt

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Obter versão
      id: get_version
      run: |
        $version = Get-Content -Path src/version.txt -Raw
        $version = $version.Trim()
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Gerar executável
      run: |
        pyinstaller --onefile --windowed --name SineApp `
        --paths "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages" `  # Caminho explícito
        --add-data "src/assets/icons/*;assets/icons/" `
        --add-data "src/config.json;." `
        --add-data "src/version.txt;." `
        --add-binary "C:\hostedtoolcache\windows\Python\3.11.9\x64\DLLs/python311.dll;." `  # Inclui a DLL
        src/main.py

    - name: Publicar no GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SineApp.exe
        tag_name: v${{ steps.get_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}