name: Build Automático e Publicação

on:
  push:
    branches: [main]

permissions:
  contents: write  # Permissão necessária para criar releases

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 25

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar ferramentas básicas
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Gerar requirements.txt
      run: |
        pip install pipreqs
        pipreqs src/ --force --savepath requirements.txt --ignore *.json,*.txt,assets
        echo "pyinstaller==6.8.0" >> requirements.txt
        echo "bcrypt==4.1.2" >> requirements.txt
        echo "cffi==1.16.0" >> requirements.txt
        echo "pywin32==306" >> requirements.txt
        sed -i '/python_bcrypt/d' requirements.txt

    - name: Instalar pacotes
      run: |
        pip install -r requirements.txt

    - name: Obter versão
      id: get_version
      run: |
        $version = Get-Content -Path src/version.txt -Raw
        $version = $version.Trim()
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Compilar com PyInstaller
      shell: pwsh
      run: |
        pyinstaller --clean --onefile --windowed `
          --name "SineApp" `
          --paths "$env:pythonLocation\Lib\site-packages" `
          --add-data "src/assets/icons/*;assets/icons/" `
          --add-data "src/config.json;." `
          --add-data "src/version.txt;." `
          --distpath "dist" `
          src/main.py

    - name: Publicar Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SineApp.exe
        tag_name: "v${{ steps.get_version.outputs.version }}"  # Corrigido
        name: "Release v${{ steps.get_version.outputs.version }}"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}